In [48]:
prices_yesterday = [-10, -7, -5, -8, -11, -9, -12]

In [49]:
max(prices_yesterday)

-5

In [36]:
def get_max_profit(prices):
    
    profit = list()
    for item in prices:
        right, left_min = prices.pop(), min(prices)
        diff = right - left_min
        profit.append(diff)
    return max(profit)

In [39]:
  get_max_profit(prices_yesterday)

6

Create a function that takes a Roman numeral as its argument and returns its value as a numeric decimal integer. You don't need to validate the form of the Roman numeral.

Modern Roman numerals are written by expressing each decimal digit of the number to be encoded separately, starting with the leftmost digit and skipping any 0s. So 1990 is rendered "MCMXC" (1000 = M, 900 = CM, 90 = XC) and 2008 is rendered "MMVIII" (2000 = MM, 8 = VIII). The Roman numeral for 1666, "MDCLXVI", uses each letter in descending order.

Example:

solution('XXI') # should return 21
C# RomanDecode.Solution("XXI") -- should return 21

def solution(roman):
  """complete the solution by transforming the roman numeral into an integer"""
    pass

Create a RomanNumerals helper that can convert a roman numeral to and from an integer value. The class should follow the API demonstrated in the examples below. Multiple roman numeral values will be tested for each helper method.

Modern Roman numerals are written by expressing each digit separately starting with the left most digit and skipping any digit with a value of zero. In Roman numerals 1990 is rendered: 1000=M, 900=CM, 90=XC; resulting in MCMXC. 2008 is written as 2000=MM, 8=VIII; or MMVIII. 1666 uses each Roman symbol in descending order: MDCLXVI.

Examples:

RomanNumerals.to_roman(1000) # should return 'M'
RomanNumerals.from_roman('M') # should return 1000

Create a function taking a positive integer as its parameter and returning a string containing the Roman Numeral representation of that integer.

Modern Roman numerals are written by expressing each digit separately starting with the left most digit and skipping any digit with a value of zero. In Roman numerals 1990 is rendered: 1000=M, 900=CM, 90=XC; resulting in MCMXC. 2008 is written as 2000=MM, 8=VIII; or MMVIII. 1666 uses each Roman symbol in descending order: MDCLXVI.

Example:

solution(1000) # should return 'M'
Help:

Symbol    Value
I          1
V          5
X          10
L          50
C          100
D          500
M          1,000
Remember that there can't be more than 3 identical symbols in a row.

More about roman numerals - http://en.wikipedia.org/wiki/Roman_numerals

def solution(n):
    # TODO convert int to roman string
    return

In [3]:
import collections
import string

In [99]:
import math

class PaginationHelper:

  # The constructor takes in an array of items and a integer indicating
  # how many items fit within a single page
  def __init__(self, collection, items_per_page):
      self.collection = collection
      self.items_per_page = items_per_page      
  
  # returns the number of items within the entire collection
  def item_count(self):
      return len(self.collection)      
  
  # returns the number of pages
  def page_count(self):
    raw = float(self.item_count())/self.items_per_page
    nfloat = math.modf(raw)[0]
    nint =   math.modf(raw)[1]
    
    if nfloat > 0:
        return int(nint) + 1
    else:
        return int(nint)     
  
  # returns the number of items on the current page. page_index is zero based
  # this method should return -1 for page_index values that are out of range
  def page_item_count(self,page_index):
        page = page_index + 1 # page number for 0 index
        theor_items = page * self.items_per_page
        items_used = (page - 1) * self.items_per_page
        diff = self.item_count() - items_used
        if page <= self.page_count():
            if diff <= self.items_per_page:
                return abs(diff)                               
            else:
                return self.items_per_page 
                
        else:
            return -1      
  
  # determines what page an item is on. Zero based indexes.
  # this method should return -1 for item_index values that are out of range
  def page_index(self,item_index):
        item_number = float(item_index) + 1 # account for 0 index
        page_quot = item_number/self.items_per_page
        page = int(math.ceil(page_quot))
        if (page <= self.page_count()) and (item_index >= 0) and (item_number <= self.item_count()):
            return page - 1 # returning the index, not the page   
        else:
            return -1

In [100]:
helper = PaginationHelper([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24], 10)

In [101]:
helper.page_index(2)

0

In [102]:
helper.page_index(23)

2

In [103]:
helper.page_index(24)

-1

In [177]:
def scramble(s1,s2):
    
    s1_count = collections.Counter([c for c in s1 if c in s2])
    s2_count = collections.Counter(s2)
    
    for c in s2:
        if c in s1_count and (s1_count[c] >= s2_count[c]):
            print c, s1_count[c], s2_count[c]
    else:
        return False
    
    return True

    

scramble('rkqodlw','world')

scramble('scriptjava','javascript')

s1 = 'rkqodlw'
s2 = 'world'

[c for c in s1 if c in s2]

Test.assert_equals(scramble('rkqodlw','world'),True)
Test.assert_equals(scramble('cedewaraaossoqqyt','codewars'),True)
Test.assert_equals(scramble('katas','steak'),False)
Test.assert_equals(scramble('scriptjava','javascript'),True)
Test.assert_equals(scramble('scriptingjava','javascript'),True)

In [85]:
def anagrams(word, words):
    word_count = dict(collections.Counter(word))
    words_count = [dict(collections.Counter(w)) for w in words]
    
    anagrams = []
    
    for index, item in enumerate(words_count):
        if cmp(word_count, item) == 0:
            anagrams.append(words[index])
        else:
            continue
    
    return anagrams

In [86]:
anagrams('abba', ['aabb', 'abcd', 'bbaa', 'dada'])

['aabb', 'bbaa']

Test.assert_equals(anagrams('abba', ['aabb', 'abcd', 'bbaa', 'dada']), ['aabb', 'bbaa'])
Test.assert_equals(anagrams('racer', ['crazer', 'carer', 'racar', 'caers', 'racer']), ['carer', 'racer'])

## GG

In [4]:
abc = "abcdefghijklmnopqrstuvwxyz"
key = "keyword"
# cipher = keyword_cipher(abc, key);

In [28]:
import collections
import string

class keyword_cipher(object):
    
    
    def __init__(self, abc, keyword):
        self.abc = abc
        self.keyword = "".join(collections.OrderedDict.fromkeys(keyword))
        self.replaced = "".join([c for c in abc if c not in self.keyword])
        self.key = "".join([self.keyword, self.replaced])
        self.encoder = dict(zip(self.abc, self.key))
        self.decoder = dict(zip(self.key, self.abc))        
        
        
    def encode(self, message): 
        encoded = ""
        for c in message:
            if c in self.abc:
                encoded = encoded + self.encoder[c.lower()]
            else:
                encoded = encoded + c
            
        return encoded
    
    def decode(self, message):
        decoded = ""
        for c in message:
            if c in self.abc:
                decoded = decoded + self.decoder[c.lower()]
            else:
                decoded = decoded + c
            
        return decoded

In [29]:
cipher = keyword_cipher(abc, key)

In [30]:
cipher.encode('abc.')

'key.'

In [31]:
cipher.decode('a_bc&*83')

'h_ij&*83'

a_bc&*83
'tfo' should equal 't_fo&*83'

In [90]:
import re
import string
def okkOokOo(s):
    
    s = re.sub(r',\s*','',s)
    s = re.split(r'[!?]', s)
    nums = [len(el) for el in s]
    
    alphabet = string.ascii_lowercase
    
    words = [alphabet[i-1] for i in nums]
    
    return nums,words

In [ ]:
import re
import string
def rot13(message):
    
    # first task, construct dict for lookup
    
    rot = 13 # integer to shift/rotate by
    letters = string.ascii_lowercase
    wrap = rot - len(letters) # 13 - 26 = -13
    l1 = list(letters)
    l2 = [letters[(letters.index(letter) + wrap)] for letter in letters] # translate each letter
    look = dict(zip(l2,l1)) # create dict for use as lookup 
    
    # second task, perform the translation
    
    message = message.split(" ")
    store = [] # empty list to store translated characters to join later
    for sub in message:
        subl = list(sub)
        for el in subl:
            if el.isalpha() and el.islower():
                store.append(look[el.lower()])
            elif el.isalpha() and el.isupper():
                store.append(look[el.lower()].upper())
            else:
                store.append(el)
            
        store.append(" ") # add a space between original elements
        
    new_message = "".join(store[:-1]) # join 'em up 
    
    
    return new_message

In [91]:
okkOokOo('Ok, Ook, Ooo? Okk, Ook, Ok? Okk, Okk, Oo? Okk, Okk, Oo? Okk, Okkkk!')

([8, 9, 9, 9, 9, 0], ['h', 'i', 'i', 'i', 'i', 'z'])

In [87]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [12]:
string.punctuation.replace(',','')

'!"#$%&\'()*+-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude = set(string.punctuation.replace(',','')) # string with all punctuation except comma
    
    s = ''.join(ch for ch in s if ch not in exclude)
    
    return s

In [1]:
import pandas as pd

In [6]:
pd.read_table('https://raw.githubusercontent.com/baumanab/seattle_tides/master/data/tide_days.tsv')

,Level,start_stop,Date,Time,DateTime,Day,Sunrise_dt,Sunset_dt
0,9.80,wait,2015-08-23,00:00:00,2015-08-23 00:00:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
1,9.71,wait,2015-08-23,00:06:00,2015-08-23 00:06:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
2,9.60,wait,2015-08-23,00:12:00,2015-08-23 00:12:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
3,9.50,wait,2015-08-23,00:18:00,2015-08-23 00:18:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
4,9.38,wait,2015-08-23,00:24:00,2015-08-23 00:24:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
5,9.26,wait,2015-08-23,00:30:00,2015-08-23 00:30:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
6,9.13,wait,2015-08-23,00:36:00,2015-08-23 00:36:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
7,9.00,wait,2015-08-23,00:42:00,2015-08-23 00:42:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
8,8.86,wait,2015-08-23,00:48:00,2015-08-23 00:48:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
9,8.72,wait,2015-08-23,00:54:00,2015-08-23 00:54:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
10,8.57,wait,2015-08-23,01:00:00,2015-08-23 01:00:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
11,8.41,wait,2015-08-23,01:06:00,2015-08-23 01:06:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
12,8.25,wait,2015-08-23,01:12:00,2015-08-23 01:12:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
13,8.09,wait,2015-08-23,01:18:00,2015-08-23 01:18:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
14,7.92,wait,2015-08-23,01:24:00,2015-08-23 01:24:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
15,7.75,wait,2015-08-23,01:30:00,2015-08-23 01:30:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
16,7.57,wait,2015-08-23,01:36:00,2015-08-23 01:36:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
17,7.40,wait,2015-08-23,01:42:00,2015-08-23 01:42:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
18,7.21,wait,2015-08-23,01:48:00,2015-08-23 01:48:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
19,7.03,wait,2015-08-23,01:54:00,2015-08-23 01:54:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
20,6.84,wait,2015-08-23,02:00:00,2015-08-23 02:00:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
21,6.65,wait,2015-08-23,02:06:00,2015-08-23 02:06:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
22,6.46,wait,2015-08-23,02:12:00,2015-08-23 02:12:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
23,6.27,wait,2015-08-23,02:18:00,2015-08-23 02:18:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
24,6.08,wait,2015-08-23,02:24:00,2015-08-23 02:24:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
25,5.88,wait,2015-08-23,02:30:00,2015-08-23 02:30:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
26,5.69,wait,2015-08-23,02:36:00,2015-08-23 02:36:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
27,5.49,wait,2015-08-23,02:42:00,2015-08-23 02:42:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
28,5.30,wait,2015-08-23,02:48:00,2015-08-23 02:48:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
29,5.10,wait,2015-08-23,02:54:00,2015-08-23 02:54:00,235,2015-08-23 06:15:19,2015-08-23 20:08:00
...,...,...,...,...,...,...,...,...
37140,12.40,wait,2016-08-20,20:00:00,2016-08-20 20:00:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37141,12.33,wait,2016-08-20,20:06:00,2016-08-20 20:06:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37142,12.25,wait,2016-08-20,20:12:00,2016-08-20 20:12:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37143,12.16,wait,2016-08-20,20:18:00,2016-08-20 20:18:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37144,12.06,wait,2016-08-20,20:24:00,2016-08-20 20:24:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37145,11.95,wait,2016-08-20,20:30:00,2016-08-20 20:30:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37146,11.83,wait,2016-08-20,20:36:00,2016-08-20 20:36:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37147,11.70,wait,2016-08-20,20:42:00,2016-08-20 20:42:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37148,11.56,wait,2016-08-20,20:48:00,2016-08-20 20:48:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37149,11.41,wait,2016-08-20,20:54:00,2016-08-20 20:54:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37150,11.25,wait,2016-08-20,21:00:00,2016-08-20 21:00:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37151,11.08,wait,2016-08-20,21:06:00,2016-08-20 21:06:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37152,10.91,wait,2016-08-20,21:12:00,2016-08-20 21:12:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37153,10.73,wait,2016-08-20,21:18:00,2016-08-20 21:18:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37154,10.54,wait,2016-08-20,21:24:00,2016-08-20 21:24:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37155,10.34,wait,2016-08-20,21:30:00,2016-08-20 21:30:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37156,10.14,wait,2016-08-20,21:36:00,2016-08-20 21:36:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37157,9.93,wait,2016-08-20,21:42:00,2016-08-20 21:42:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37158,9.71,wait,2016-08-20,21:48:00,2016-08-20 21:48:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37159,9.49,wait,2016-08-20,21:54:00,2016-08-20 21:54:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37160,9.27,wait,2016-08-20,22:00:00,2016-08-20 22:00:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37161,9.04,wait,2016-08-20,22:06:00,2016-08-20 22:06:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37162,8.81,wait,2016-08-20,22:12:00,2016-08-20 22:12:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37163,8.57,wait,2016-08-20,22:18:00,2016-08-20 22:18:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37164,8.33,wait,2016-08-20,22:24:00,2016-08-20 22:24:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37165,8.09,wait,2016-08-20,22:30:00,2016-08-20 22:30:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37166,7.84,wait,2016-08-20,22:36:00,2016-08-20 22:36:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37167,7.59,wait,2016-08-20,22:42:00,2016-08-20 22:42:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37168,7.35,wait,2016-08-20,22:48:00,2016-08-20 22:48:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09
37169,7.10,wait,2016-08-20,22:54:00,2016-08-20 22:54:00,233,2016-08-20 06:12:16,2016-08-20 20:12:09